approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: true

npmMinimalAgeGate: 0

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

packageExtensions:
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  autoprefixer@*:
    dependencies:
      postcss: "*"
  bunyan@*:
    dependencies:
      source-map-support: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  express@*:
    dependencies:
      ejs: "*"
  next@*:
    dependencies:
      autoprefixer: "*"
      postcss: "*"
  tailwindcss@*:
    dependencies:
      "@tailwindcss/line-clamp": "*"
  tr46@*:
    dependencies:
      punycode: "*"
  whatwg-url@*:
    dependencies:
      punycode: "*"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
