compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

packageExtensions:
  "@aws-sdk/credential-provider-ini@*":
    dependencies:
      "@aws-sdk/client-sts": ^3.645.0
  "@aws-sdk/credential-provider-web-identity@*":
    dependencies:
      "@aws-sdk/client-sts": ^3.645.0
  "@aws-sdk/token-providers@*":
    dependencies:
      "@aws-sdk/client-sso-oidc": ^3.645.0
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  autoprefixer@*:
    dependencies:
      postcss: "*"
  bunyan@*:
    dependencies:
      source-map-support: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  express@*:
    dependencies:
      ejs: "*"
  next@*:
    dependencies:
      autoprefixer: "*"
      postcss: "*"
  tailwindcss@*:
    dependencies:
      "@tailwindcss/line-clamp": "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
