compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

packageExtensions:
  # Patching vulnerabile dependencies
  mock-aws-s3@4.0.2:
    dependencies:
      underscore: "1.12.1"
  postcss-modules-sync@1.0.0:
    dependencies:
      generic-names: "4.0.0"
  # Open Next
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  next@*:
    dependencies:
      "autoprefixer": "*"
      "postcss": "*"
  autoprefixer@*:
    dependencies:
      "postcss": "*"
  "@aws-sdk/credential-provider-web-identity@*":
    dependencies:
      "@aws-sdk/client-sts": "^3.645.0"
  "@aws-sdk/credential-provider-ini@*":
    dependencies:
      "@aws-sdk/client-sts": "^3.645.0"
  "@aws-sdk/token-providers@*":
    dependencies:
      "@aws-sdk/client-sso-oidc": "^3.645.0"
  express@*:
    dependencies:
      ejs: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
