compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

packageExtensions:
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  next-virtual@*:
    dependencies:
      "autoprefixer": "*"
      "postcss": "*"
  next@*:
    dependencies:
      "autoprefixer": "*"
      "postcss": "*"
  autoprefixer@*:
    dependencies:
      "postcss": "*"
  "@aws-sdk/credential-provider-web-identity@*":
    dependencies:
      "@aws-sdk/client-sts": "^3.645.0"
  "@aws-sdk/credential-provider-ini@*":
    dependencies:
      "@aws-sdk/client-sts": "^3.645.0"
  "@aws-sdk/token-providers@*":
    dependencies:
      "@aws-sdk/client-sso-oidc": "^3.645.0"
  express@*:
    dependencies:
      ejs: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
