name: 'Goldstack Setup'
description: 'Gets things ready for running scripts'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        verbose: false
        arch: amd64
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10'
    - name: Install Yarn
      run: npm install -g yarn@1.22.11
      shell: bash
    - name: Install
      run: yarn install
      shell: bash
    - name: Build
      run: yarn build
      shell: bash
