name: 'Goldstack Setup'
description: 'Gets things ready for running scripts'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - name: Install Yarn
      run: npm install -g yarn@1.22.11
      shell: bash
    - name: Install
      run: yarn install
      shell: bash
    - name: Build
      run: yarn build
      shell: bash
