name: Template Deployment for PROD

on: [push]

jobs:
  build:
    name: 'Deploy build set'
    strategy:
      fail-fast: false
      matrix:
        deploy-set:
          [
            'backend-go-gin',
            'backend-lambda-api',
            'backend-nodejs-express',
            'nextjs',
            'nextjs-bootstrap',
            'no-infra',
            'email-send',
            's3',
            'static-website',
            'user-management',
            'dynamodb',
            'server-side-rendering',
            'hetzner-vps',
            'lambda-python-job',
            'lambda-node-trigger',
          ]
    if: ${{ contains(github.event.head_commit.message, 'trigger_template_deploy_prod') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Goldstack repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
          token: ${{secrets.BUILD_TOKEN}}
      - uses: ./.github/actions/goldstack-setup
      - uses: actions/setup-java@v4 # used for local DynamoDB
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-java@v4 # used for local DynamoDB
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run build set
        run: |
          cd workspaces/apps/packages/template-management-cli
          yarn cli deploy-set \
            --set ${{ matrix.deploy-set }} \
            --deployment prod \
            --repo goldstack-prod \
            --skipTests true \
            --workDir tmp \
            --emailResultsTo false
        env:
          AWS_USER_NAME: goldstack-prod
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
